name: Generate PHPDoc

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install project dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install phpDocumentor globally
      run: composer global require phpdocumentor/phpdocumentor:^3.4

    - name: Generate PHPDoc
      run: |
        mkdir -p docs
        ~/.composer/vendor/bin/phpdoc -d src -t docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
