name: Generate PHPDoc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Clear Composer Cache and install dependencies
      run: |
        rm -rf vendor composer.lock
        composer clear-cache
        composer install --prefer-dist --no-progress --no-scripts

    - name: Generate PHPDoc
      run: |
        mkdir -p docs
        vendor/bin/phpdoc -d src -t docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
