name: Generate phpDocumentor Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up PHP # Цей крок все ще потрібен для встановлення залежностей вашого проекту
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Або потрібна тобі версія PHP

    - name: Clear Composer Cache
      run: composer clear-cache
      shell: bash

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Project Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate Documentation with Docker
      # Використовуємо офіційний образ phpDocumentor
      # -v "${{ github.workspace }}:/data" монтує ваш репозиторій у контейнер
      # /data - це робочий каталог у контейнері
      # phpdoc -c phpdoc.xml.dist запускає phpdoc з вашим конфігураційним файлом
      run: docker run --rm -v "${{ github.workspace }}:/data" phpdocumentor/phpdocumentor:3 phpdoc -c phpdoc.xml.dist
      # Якщо виникнуть проблеми з дозволами, спробуйте додати --user $(id -u):$(id -g) після --rm
      # run: docker run --rm --user $(id -u):$(id -g) -v "${{ github.workspace }}:/data" phpdocumentor/phpdocumentor:3 phpdoc -c phpdoc.xml.dist


    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
